version: "3"

services:
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_URL: postgresql://test:test@localhost:5432/test?sslmode=disable

      PGDATA: /data
      TZ: 'GMT+5'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 10s
      retries: 5
  migrate:
    depends_on:
      db:
        condition: service_healthy
    image: migrate/migrate
    volumes:
       - ./migrate:/migrations
    command: ["-path", "./migrations", "-database",  "postgresql://test:test@db:5432/test?sslmode=disable", "up"]  
  web:
    image: ${NAME}:${VERSION}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        NAME: ${NAME}
        VERSION: ${VERSION}
    environment:
      TZ: "Asia/Tashkent"
      PG_URL: postgresql://test:test@db:5432/test?sslmode=disable
      VERSION: 1.0.0
      CONF_PATH: "config/conf.yaml"
      PORT: 9000
    volumes:
      - ./volumes/web/log:/app/log
      - ../src/config/conf.yaml:/app/config/conf.yaml
    depends_on:
      db:
        condition: service_healthy
    stop_grace_period: 2s
    ports:
      - 127.0.0.1:9000:9000
